package net.yggawg.mobile.vpn

import android.util.Base64
import awgmobile.Awgmobile
import awgmobile.Backend
import kotlinx.coroutines.*
import net.yggawg.mobile.AppLogger
import net.yggawg.mobile.config.AwgConfig

/**
 * Wrapper around amneziawg.aar (gomobile bindings).
 *
 * Java API (generated by gomobile):
 *   awgmobile.Backend
 *     start(String settings, long mtu)
 *     stop()
 *     sendPacket(byte[])   – plaintext in (to be encrypted + sent)
 *     recvPacket(): byte[] – decrypted out (blocking)
 *
 *   awgmobile.Awgmobile.buildUAPISettings(
 *     privateKeyHex, publicKeyHex, presharedKeyHex,
 *     endpoint, allowedIPs, persistentKeepalive,
 *     jc, jmin, jmax,
 *     s1, s2, s3, s4,
 *     h1, h2, h3, h4,   (String, raw spec)
 *     i1, i2, i3, i4, i5
 *   ): String
 */
class AwgManager(
    private val onPacketOut: (ByteArray) -> Unit,
    /** Called on IO thread when AWG layer state changes. */
    private val onStatusChange: (LayerState) -> Unit = {},
) {
    companion object {
        private const val TAG = "AwgManager"
        private const val AWG_MTU = 1500L
    }

    @Volatile private var backend: Backend? = null
    @Volatile private var activeScope: CoroutineScope? = null

    fun start(config: AwgConfig) {
        if (backend != null) return
        val protocolLabel = if (config.isAwg) "AmneziaWG" else "WireGuard"
        AppLogger.i(TAG, "Starting $protocolLabel → ${config.endpoint}")

        val settings = buildUAPI(config)
        AppLogger.d(TAG, "UAPI settings:\n${settings.replace(
            Regex("(?m)^(private_key|preshared_key)=.+$"), "$1=[REDACTED]")}")

        val b = Backend()
        try {
            b.start(settings, AWG_MTU)
            backend = b
            onStatusChange(LayerState.STARTING)   // UP only after first decrypted packet
            val scope = CoroutineScope(Dispatchers.IO + SupervisorJob())
            activeScope = scope
            scope.launch { readLoop(b, scope) }
            AppLogger.i(TAG, "$protocolLabel started")
        } catch (e: Exception) {
            AppLogger.e(TAG, "Failed to start $protocolLabel: ${e.javaClass.simpleName}: ${e.message}")
            onStatusChange(LayerState.ERROR)
        }
    }

    fun stop() {
        activeScope?.cancel(); activeScope = null
        val b = backend ?: return
        backend = null
        try { b.stop() } catch (e: Exception) { AppLogger.w(TAG, "stop: $e") }
        AppLogger.i(TAG, "WG backend stopped")
    }

    /** Write a plaintext IP packet into the AWG stack for encryption and sending. */
    fun writePacket(packet: ByteArray) {
        try {
            backend?.sendPacket(packet)
        } catch (e: Exception) {
            AppLogger.w(TAG, "sendPacket: $e")
        }
    }

    /**
     * Inject a WireGuard protocol packet (encrypted, from the server via Yggdrasil)
     * into the AWG device for decryption.
     */
    fun sendWGPacket(wgPacket: ByteArray) {
        try {
            backend?.sendWGPacket(wgPacket)
        } catch (e: Exception) {
            AppLogger.w(TAG, "sendWGPacket: $e")
        }
    }

    /**
     * Return the next outbound WireGuard protocol packet (encrypted) that AWG
     * wants to send to the server. Blocks until available or device is stopped.
     */
    fun recvWGPacket(): ByteArray? {
        return try {
            backend?.recvWGPacket()
        } catch (e: Exception) {
            AppLogger.w(TAG, "recvWGPacket: $e")
            null
        }
    }

    // -------------------------------------------------------------------------

    private fun readLoop(b: Backend, scope: CoroutineScope) {
        var firstPacket = true
        while (scope.isActive && backend != null) {
            val pkt = try {
                b.recvPacket()
            } catch (e: Exception) {
                if (scope.isActive) AppLogger.w(TAG, "recvPacket: $e")
                null
            }
            if (pkt != null) {
                if (firstPacket) {
                    firstPacket = false
                    AppLogger.i(TAG, "WG handshake complete — tunnel UP (${pkt.size} bytes)")
                    onStatusChange(LayerState.UP)
                }
                if (pkt.isNotEmpty()) {
                    onPacketOut(pkt)
                }
            }
        }
    }

    // -------------------------------------------------------------------------
    // UAPI settings builder
    // -------------------------------------------------------------------------

    /**
     * Build a WireGuard/AmneziaWG UAPI config string using the official
     * [Awgmobile.buildUAPISettings] helper from the AAR.
     *
     * All params map 1-to-1 to the official amneziawg-go UAPI keys.
     * chanBind handles all actual routing — no real UDP socket is opened.
     */
    private fun buildUAPI(c: AwgConfig): String = Awgmobile.buildUAPISettings(
        c.privateKey.decodeBase64ToHex(),
        c.publicKey.decodeBase64ToHex(),
        c.presharedKey?.decodeBase64ToHex() ?: "",
        c.endpoint,
        c.allowedIPs,
        (c.persistentKeepalive ?: 0).toLong(),
        (c.jc   ?: 0).toLong(),
        (c.jmin ?: 0).toLong(),
        (c.jmax ?: 0).toLong(),
        (c.s1   ?: 0).toLong(),
        (c.s2   ?: 0).toLong(),
        (c.s3   ?: 0).toLong(),
        (c.s4   ?: 0).toLong(),
        c.h1   ?: "",
        c.h2   ?: "",
        c.h3   ?: "",
        c.h4   ?: "",
        c.i1   ?: "",
        c.i2   ?: "",
        c.i3   ?: "",
        c.i4   ?: "",
        c.i5   ?: "",
    )

    // WireGuard UAPI uses lowercase hex keys (32 bytes = 64 hex chars), not base64
    private fun String.decodeBase64ToHex(): String {
        val bytes = Base64.decode(this, Base64.DEFAULT)
        return bytes.joinToString("") { "%02x".format(it) }
    }
}
